#### Name: Nihal Azman
#### Id:i23b0034s14

In [2]:
import numpy as np

### Problem 1

In [5]:
x=np.array([10])
y=np.array([25])
z=np.array([33])
x=np.hstack((x, z))
y=np.hstack((y, z))
x=x+z
print(x)

[43 66]


#### Problem 2

In [6]:
x=np.array([[10, 12], [13, 3], [2, 2]])
x=x*5
print(x)

[[50 60]
 [65 15]
 [10 10]]


### Problem 3

In [7]:
x = np.eye(10)
x=x*5
print(x)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


### Problem 4

In [8]:
x=np.arange(100, 100+5*20, 5)
x=x.reshape((2,5,2))
print(x)

[[[100 105]
  [110 115]
  [120 125]
  [130 135]
  [140 145]]

 [[150 155]
  [160 165]
  [170 175]
  [180 185]
  [190 195]]]


### Problem 5

In [10]:
a=np.array([[1,2],[3,4]])
b=np.array([[15,66],[20,25]])
m=np.hstack((a,b))
print(m)

[[ 1  2 15 66]
 [ 3  4 20 25]]


### Problem 6

In [11]:
a=np.array([[1,2],[3,4]])
b=np.array([[15,66],[20,25]])
mv=np.vstack((a,b))
print(mv)

[[ 1  2]
 [ 3  4]
 [15 66]
 [20 25]]
